routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\ArticleController as AdminArticleController;
use App\Http\Controllers\User\ArticleController as UserArticleController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;


Route::post('/login', [LoginController::class, 'login']);

Auth::routes(['verify' => true]);
Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::middleware(['admin', 'auth'])->prefix('admin')->name('admin.')->group(function () {
    Route::resource('users', UserController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('articles', AdminArticleController::class);
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::resource('articles', UserArticleController::class);
});


Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/read-more/{id}', [App\Http\Controllers\HomeController::class, 'readMore'])->name('read-more');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @property mixed category_id
 * @property mixed body
 * @property mixed title
 * @property mixed status
 * @property  user_id
 */
class Article extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'category_id',
        'title',
        'body',
        'status',
        'image'
    ];


    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }


    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable  implements MustVerifyEmail
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function articles(){
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\MailController;
use App\Http\Requests\ArticlesRequest;
use App\Models\Category;
use App\Models\User;
use Illuminate\Http\Request;
use App\Models\Article;
use Illuminate\Support\Facades\Auth;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::all();
        return view('admin.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all()->pluck('name', 'id');

        return view('admin.articles.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArticlesRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticlesRequest $request)
    {

        $article = new Article;
        $article->user_id = Auth::id();
        $article->title = $request->get('title');
        $article->body = $request->get('body');
        $article->category_id = $request->get('category_id');
        $article->status = (int)$request->get('status');
        if ($request->image) {
            $fileName = time() . '.' . $request->image->extension();
            $request->image->move(public_path('uploads'), $fileName);
            $article->image = $fileName;
        }
        $article->save();

        return redirect()->route('admin.articles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::where('id', $id)->with('category')->first();
        $categories = Category::all()->pluck('name', 'id');

        return view('admin.articles.edit', compact('article', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ArticlesRequest $request
     * @param  int $id
     * @return void
     */
    public function update(ArticlesRequest $request, $id)
    {
        $article = Article::find($id);

        $article->title = $request->get('title');
        $article->body = $request->get('body');
        $article->category_id = $request->get('category_id');
        $article->status = (int)$request->get('status');
        if ($request->image) {
            $fileName = time() . '.' . $request->image->extension();
            $request->image->move(public_path('uploads'), $fileName);
            $article->image = $fileName;
        }
        $article->save();

        if ($article->user_id != Auth::id()) {
            $user = User::where('id', $article->user_id)->first();
            MailController::notifyUser($user, $article, 'edited');
        }

        return redirect()->route('admin.articles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::find($id);
        $articleCopy = clone $article;

        if (!$article) {
            return redirect()->route('admin.articles.index');
        }
        $article->delete();

        if ($articleCopy->user_id != Auth::id()) {
            $user = User::where('id', $articleCopy->user_id)->first();
            MailController::notifyUser($user, $articleCopy, 'deleted');
        }

        // redirect
        return redirect()->route('admin.articles.index');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/ArticleController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\MailController;
use App\Http\Requests\ArticlesRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\Article;
use Illuminate\Support\Facades\Auth;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::where('user_id', Auth::id())->get();
        return view('user.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all()->pluck('name', 'id');

        return view('user.articles.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArticlesRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticlesRequest $request)
    {

        $article = new Article;
        $article->user_id = Auth::id();
        $article->title = $request->get('title');
        $article->body = $request->get('body');
        $article->category_id = $request->get('category_id');
        $article->status = (int)$request->get('status');
        if ($request->image) {
            $fileName = time() . '.' . $request->image->extension();
            $request->image->move(public_path('uploads'), $fileName);
            $article->image = $fileName;
        }
        $article->save();


        return redirect()->route('articles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::where('id', $id)->with('category')->first();
        $categories = Category::all()->pluck('name', 'id');

        //todo send email to admin

        return view('user.articles.edit', compact('article', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ArticlesRequest $request
     * @param  int $id
     * @return void
     */
    public function update(ArticlesRequest $request, $id)
    {
        $article = Article::find($id);
        $article->title = $request->get('title');
        $article->body = $request->get('body');
        $article->category_id = $request->get('category_id');
        $article->status = (int)$request->get('status');
        if ($request->image) {
            $fileName = time() . '.' . $request->image->extension();
            $request->image->move(public_path('uploads'), $fileName);
            $article->image = $fileName;
        }
        $article->save();

        MailController::notifyAdmin(Auth::user(), $article);

        return redirect()->route('articles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::find($id);

        if (!$article) {
            return redirect()->route('articles.index');
        }
        $article->delete();

        // redirect
        return redirect()->route('articles.index');
    }
}

resources/views/user/articles/create.blade.php
@extends('layouts.main')
@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Articles</h1>
    </div>

    {!! Form::open(['url' => route('articles.store'), 'method' => 'post', 'enctype'=>"multipart/form-data"]) !!}
    <div class="row g-3">
        <div class="col-10">
            <label for="title" class="form-label">Title</label>
            {!! Form::text('title', '', ['class' => 'form-control']) !!}

            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="col-10">
            <label for="title" class="form-label">Body</label>
            {!! Form::textarea('body', '', ['class' => 'form-control']) !!}

            @error('body')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="col-10">
            <label for="status" class="form-label">Status</label>
            {!! Form::select('status', [0 => 'inactive', 1 => 'active'], ['class' => 'form-control']) !!}


            @error('status')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="col-10">
            <label for="category_id" class="form-label">Status</label>
            {!! Form::select('category_id', $categories, ['class' => 'form-control']) !!}


            @error('category_id')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="col-10">
            <label for="image" class="form-label">image</label>
            {!! Form::file('image', ['class' => 'form-control']) !!}


            @error('image')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>


        <button class=" btn btn-primary" type="submit">Create</button>
    </div>
    {!! Form::close() !!}
@stop

resources/views/user/articles/edit.blade.php
@extends('layouts.main')
@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Articles</h1>
    </div>

    {!! Form::open(['url' => route('articles.update', $article->id), 'method' => 'put', 'enctype'=>"multipart/form-data"]) !!}
    <div class="row g-3">
        <div class="col-10">
            <label for="title" class="form-label">Title</label>
            {!! Form::text('title', $article->title, ['class' => 'form-control']) !!}

            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="col-10">
            <label for="title" class="form-label">Body</label>
            {!! Form::textarea('body',  $article->body, ['class' => 'form-control']) !!}

            @error('body')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="col-10">
            <label for="status" class="form-label">Status</label>
            {!! Form::select('status', [0 => 'inactive', 1 => 'active'],  $article->status, ['class' => 'form-control']) !!}


            @error('status')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="col-10">
            <label for="category_id" class="form-label">Status</label>
            {!! Form::select('category_id', $categories,$article->category->id, ['class' => 'form-control']) !!}


            @error('category_id')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="col-10">
            <label for="image" class="form-label">image</label>
            {!! Form::file('image', ['class' => 'form-control']) !!}


            @error('image')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <button class=" btn btn-primary" type="submit">Update</button>
    </div>
    {!! Form::close() !!}
@stop

resources/views/user/articles/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{route('articles.create')}}" class="btn btn-sm btn-outline-secondary">Add</a>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Image</th>
                <th>Category</th>
                <th>Status</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach($articles as $article)
                <tr>
                    <td>{{$article->id}}</td>
                    <td>{{$article->title}}</td>
                    <td>
                        @if($article->image)
                            <img width="60" src="{{url('/uploads/'.$article->image)}}">
                        @endif


                    </td>
                    <td>{{$article->category->name}}</td>
                    <td>{{$article->status ? 'Yes' : 'No'}}</td>
                    <td>
                        <a href="{{route('articles.edit',$article->id )}}" class="btn btn-success">Edit</a>
                        {!! Form::open(['method' => 'DELETE',
                                'route' => ['articles.destroy', $article->id]]) !!}
                        {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>

            @endforeach
            </tbody>
        </table>
    </div>
@stop